import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DetailsForm from "./../components/DetailsForm";
import SelectPlanForm from "./../components/SelectPlanForm";
import SummaryForm from "./../components/SummaryForm";
import ConfirmationForm from "./../components/ConfirmationForm";
import NavProgressBar from "../components/navProgress";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const [step, setStep] = useState(1);
  const totalSteps = 4;
  const [activeClassCount, setActiveCount] = useState(1);
  const [progressClassName, setClassName] = useState("progressBarStep");
  const [activeClsWidth, setActiveClsWidth] = useState();
  const [activeClass, setActiveClass] = useState();
  const router = useRouter();
  // const [isPrevDisable, setPrevDisable] = useState();
  function previous() {
    const page = step;
    if (page > 1) {
      setStep(page - 1);
      const dupactiveClassCount = activeClassCount;
      setActiveCount(dupactiveClassCount - 1);
    }
  }
  function isPrevDisable() {
    if (step == 1) {
      return true;
    } else {
      return false;
    }
  }
  function next() {
    const page = step;
    if (page > totalSteps) {
      return;
    }
    setStep(page + 1);
    const clsName = progressClassName + " " + "progressStepActive";
    setClassName(clsName);
    setActiveClass("active");
    const dupactiveClassCount = activeClassCount;
    setActiveCount(dupactiveClassCount - 1);
    // setActiveWidth();
  }

  function formOpen() {
    switch (step) {
      case 1:
        return (
          <DetailsForm
            nextBtnClick={next}
            previousBtnClick={previous}
            isPrevDisable={isPrevDisable}
          ></DetailsForm>
        );
      case 2:
        return (
          <SelectPlanForm
            nextBtnClick={next}
            previousBtnClick={previous}
          ></SelectPlanForm>
        );
      case 3:
        return (
          <SummaryForm
            nextBtnClick={next}
            previousBtnClick={previous}
          ></SummaryForm>
        );
      case 4:
        return (
          <ConfirmationForm
            nextBtnClick={next}
            previousBtnClick={previous}
          ></ConfirmationForm>
        );
      default:
        router.push("/thankyou");
        return;
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Step by Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Step By step Form</h1>
        <NavProgressBar
          progressClassName={progressClassName}
          step={step}
          activeClassCount={activeClassCount}
          totalSteps={totalSteps}
          activeClsWidth={activeClsWidth}
          activeClass={activeClass}
        ></NavProgressBar>
        {formOpen()}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
